# Generated by Django 5.1.1 on 2024-10-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_client_id_clientevent_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
