# Generated by Django 5.1.1 on 2024-10-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='total_exp',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
