# Generated by Django 5.1.1 on 2024-10-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_lat_alter_event_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reports_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
