# Generated by Django 5.1.1 on 2024-11-12 22:12

import apps.api.models
import django.db.models.deletion
from django.db import migrations, models


def set_default_client(apps, schema_editor):
    Client = apps.get_model('api', 'Client')  # Acessa o modelo Client
    first_client = Client.objects.first()
    return first_client if first_client else None  # Retorna o primeiro cliente ou None

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_alter_event_reports_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='api.client',
                default=set_default_client,  # Utiliza a função definida diretamente aqui
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_exp',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
