# Generated by Django 5.1.1 on 2024-11-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_client_alter_client_total_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
