# Generated by Django 5.1.1 on 2024-11-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_event_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='service_category',
            field=models.CharField(choices=[('arvore_caida', 'Árvore Caída'), ('alagamento', 'Alagamento'), ('cano_quebrado', 'Cano Quebrado'), ('semaforo_queimado', 'Semáforo Queimado'), ('rua_sem_pavimentacao', 'Rua Sem Pavimentação'), ('sem_agua', 'Sem Água'), ('sem_energia', 'Sem Energia')], max_length=50),
        ),
    ]
